source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'DTCoreText'
pod 'GRMustache'
pod 'GPUImage'
pod 'MBProgressHUD'
pod 'ReactiveCocoa'
pod 'SDWebImage'
pod 'TBXML'
pod 'TOWebViewController'
pod 'TTTAttributedLabel'
pod 'TPKeyboardAvoiding'
pod 'Masonry'
pod 'MJRefresh'
pod 'NYXImagesKit', '2.3'
pod 'JazzHands', '2.0.0'
pod 'CTAssetsPickerController'
pod 'PureLayout'
pod 'JCSegmentBarController'
pod 'pop'
pod 'AFNetworking','2.6.3'
pod 'AMap3DMap'  #3D地图SDK
#pod 'AMap2DMap' #2D地图SDK (2D和3D不能同时使⽤用)
pod 'AMapSearch'
pod 'UMengSocialCOM','~> 5.2.1'
pod 'JCSegmentBarController'
pod 'Pingpp'
pod 'BabyBluetooth','~> 0.6.0'
pod 'Qiniu'
pod 'RegexKitLite'
pod 'ASIHTTPRequest'
pod 'HyphenateFullSDK', :git => 'https://github.com/easemob/hyphenate-full-cocoapods.git'
pod 'GTSDK'
